services:
  # Backend Service
  - type: web
    name: moviebooker-api
    env: node
    buildCommand: cd moviebooker-api && npm install && npm run build
    startCommand: cd moviebooker-api && npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: moviebooker-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true

  # Frontend Service (Static Site)
  - type: static
    name: moviebooker-frontend
    buildCommand: cd moviebooker-frontend && npm install && npm run build
    publishDirectory: moviebooker-frontend/dist/moviebooker-frontend
    headers:
      /**:
        - key: Cache-Control
          value: no-store, no-cache
    spa: true
    envVars:
      - key: API_URL
        value: https://moviebooker-api.onrender.com

databases:
  - name: moviebooker-db
    databaseName: moviebooker
    user: moviebooker
    plan: free 